server:
  host: 127.0.0.1
  port: 8012
  path: /koi-net
koi_net:
  node_name: hackmd-processor
  node_rid: orn:koi-net.node:hackmd-processor+62eabec3-ed43-4122-94cc-ea7aa8701fde
  node_profile:
    base_url: http://hackmd-processor:8012/koi-net
    node_type: FULL
    provides:
      event: []
      state: []
  cache_directory_path: .koi/hackmd-processor
  event_queues_path: .koi/hackmd-processor/queues.json
  first_contact: http://coordinator:8080/koi-net
fetch_retry_initial: 30
fetch_retry_multiplier: 2
fetch_retry_max_attempts: 3
index_db_path: .koi/index_db/index.db
